[package]
name = "derive_enum_from_inner"
version = "0.1.0"
authors = ["sinkuu <sinkuupump@gmail.com>"]

[lib]
name = "derive_enum_from_inner"
proc-macro = true

[dependencies]
syn = "0.9.0"
quote = "0.3.3"
